const sportIcons = {
    'E Sports': 'fas fa-headset',
    'Baseball': 'fas fa-baseball-ball',
    'Softball': 'fas fa-baseball-ball',
    'Soccer': 'fas fa-futbol',
    'Futsal': 'fas fa-futbol',
    'Basketball': 'fas fa-basketball-ball',
    'Rugby League': 'fas fa-football-ball',
    'Rugby Union': 'fas fa-football-ball',
    'Football': 'fas fa-football-ball',
    'Aussie Rules': 'fas fa-football-ball',
    'Boxing': 'fap fa-boxing-glove',
    'Mixed Martial Arts': 'fap fa-boxing-glove',
    'Cycling': 'fas fa-biking',
    'Table Tennis': 'fas fa-table-tennis',
    'Golf': 'fas fa-golf-ball',
    'Hockey': 'fas fa-hockey-puck',
    'Beach Volleyball': 'fas fa-volleyball-ball',
    'Volleyball': 'fas fa-volleyball-ball',
    'Volleyball (Points)': 'fas fa-volleyball-ball',
    'Handball': 'fas fa-volleyball-ball',
    'Floorball': 'fap fa-field-hockey',
    'Horse Racing': 'fas fa-horse',
    'Politics': 'fap fa-podium-star',
    'Bandy': 'fap fa-field-hockey',
    'Field Hockey': 'fap fa-field-hockey',
    'Chess': 'fap fa-chess',
    'Cricket': 'fap fa-cricket',
    'Crossfit': 'fas fa-dumbbell',
    'Curling': 'fas fa-dumbbell',
    'Darts': 'fap fa-bullseye-arrow',
    'Darts (Legs)': 'fap fa-bullseye-arrow',
    'Snooker': 'fas fa-circle',
    'Squash': 'fap fa-racquet',
    'Tennis': 'fap fa-racquet',
    'Poker': 'fap fa-spade',
    'Motorsport': 'fas fa-flag-checkered',
    'Formula 1': 'fas fa-flag-checkered',
    'Drone Racing': 'fas fa-flag-checkered',
    'Alpine Skiing': 'fas fa-skiing',
    'Freestyle Skiing': 'fas fa-skiing',
    'Ski Jumping': 'fas fa-skiing',
    'Snow Boarding': 'fas fa-snowboarding',
    'Short Track': 'fas fa-skating',
    'Figure Skating': 'fas fa-skating',
    'Speed Skating': 'fas fa-skating',
    'Water Polo': 'fas fa-swimmer',
    'Nordic Combined': 'fas fa-skiing-nordic',
    'Biathlon': 'fas fa-skiing-nordic',
    'Cross Country': 'fas fa-running',
    'Luge': 'fap fa-sledding',
    'Bobsleigh': 'fap fa-sledding',
    'Entertainment': 'fas fa-photo-video',
    'Olympics': 'fas fa-trophy',
    'Athletics': 'fas fa-running',
    'Badminton': 'fap fa-racquet',
    'NFL': 'fas fa-football-ball',
    'NHL': 'fas fa-hockey-puck',
    'MLB': 'fas fa-baseball-ball',
    'NBA': 'fas fa-basketball-ball',
    'WNBA': 'fas fa-basketball-ball',
    'NCAA': 'fas fa-basketball-ball',
    'UFC': 'fap fa-boxing-glove',
    'Side Bet': 'fa fa-broadcast-tower'
};

function sportNameIcon(name) {
    return sportIcons[name];
}

module.exports = sportNameIcon;