const mongoose = require('mongoose');
const { Schema } = mongoose;

const TevoOrderSchema = new Schema(
    {
        user_id: { type: Schema.Types.ObjectId, ref: "User" },
        id: { type: String, required: true, index: { unique: true } },
        oid: { type: String, required: true },
        order_type: { type: String },
        substitute_order_link_id: { type: String },
        was_auto_pended: { type: String },
        was_auto_accepted: { type: String },
        was_auto_canceled: { type: String },
        pending_non_refund_payments_total: { type: Number },
        completed_non_refund_payments_total: { type: Number },
        pending_balance: { type: Number },
        shipping: { type: Number },
        service_fee: { type: Number },
        additional_expense: { type: Number },
        discount: { type: Number },
        tax: { type: Number },
        fee: { type: Number },
        refunded: { type: Number },
        returns_total: { type: Number },
        penalties_total: { type: Number },
        instructions: { type: String },
        buyer_state: { type: String },
        seller_state: { type: String },
        consignment: { type: Boolean },
        seller_cancellation_reason: { type: String },
        buyer_cancellation_reason: { type: String },
        seller_cancellation_notes: { type: String },
        buyer_cancellation_notes: { type: String },
        seller_rejection_reason: { type: String },
        buyer_rejection_reason: { type: String },
        seller_rejection_notes: { type: String },
        buyer_rejection_notes: { type: String },
        created_at: { type: Date },
        updated_at: { type: Date },
        url: { type: String },
        oth_created: { type: Boolean },
        reference: { type: String },
        created_by_ip_address: { type: String },
        substitutions: { type: Array },
        subtotal: { type: Number },
        total: { type: Number },
        balance: { type: Number },
        state: { type: String },
        child_orders: { type: Array },
        created_by: { type: Object },
        buyer: { type: Object },
        seller: { type: Object },
        billing_address: { type: Object },
        shipping_address: { type: Object },
        deliveries: { type: Array },
        notes: { type: Array },
        items: { type: Array },
        payments: { type: Array },
        client: { type: Object },
        fraud_check_status: { type: String },
        isPO: { type: Boolean },
        partner: { type: Boolean }
    },
    { timestamps: true, },
);

const TevoOrder = mongoose.model('TevoOrder', TevoOrderSchema);

module.exports = TevoOrder;
